apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/my-cluster/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system