apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
resources:
  - namespace.yaml
  - source.yaml
  - kube-prometheus-stack/release.yaml