apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/my-cluster/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system