apiVersion: apps/v1
kind: Deployment
metadata:
  name: cabot-book
  namespace: my-cluster
spec: 
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: cabot-book
  template:
    metadata:
      labels:
        app: cabot-book
    spec:
      containers:
      - name: cabot-book
        image: ghcr.io/dgunzy/cabot-book:latest
        ports:
          - name: web
            containerPort: 8080 
       
        envFrom:
        - secretRef:
            name: cabot-book-env