apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cabot-book 
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/my-cluster/apps/cabot-book
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system