apiVersion: v1
kind: Secret
metadata:
    name: cabot-book-env
    namespace: my-cluster
type: Opaque
stringData:
    APP_ENV: ENC[AES256_GCM,data:iBiNbdI=,iv:LdixEZZg3dY9DksU+DVzALhOINfJAdfaFKA2e4ZNkN0=,tag:OOA//bRATtx1atlCgOBiYw==,type:str]
    CALLBACK_URL: ENC[AES256_GCM,data:KUA9BXZSlhRUiTloi3wZv0o9CZ5rhcZu3SBV10mVtgZwSCzget6Fww9TRQX85UR3uw==,iv:NcyLXC6/XgU1UFRH5rDPh6RKJ8FElyRFSbWXeie1Z7M=,tag:AjWSF1QUaZQP3LADjXBEIQ==,type:str]
    DBAUTH: ENC[AES256_GCM,data:ZlE9bqiwlc2B6hX53TW9iIoTOgeZDJ4bd8dtj1XWtPeZI++O5M+8q31fPMIJDzPXydFd40mW9fbzHH/nYoGTHl4Vvo4i0bLc41E7u+tdq6Yzt9Rmzm10wJpCK6+4m71bkTUvEGbL00mrEeAZMrmtjPQO0w4wuYZTNoByq8ZNNvrxR891Gwxk+RKlgQYMw5Ur3luojwSiQ+hJEBmjyWkyDhx2203EhOGKn5rZE+13gyCGkuZXGj/ke58E9RDEHGeLF0Oyfd574at4P0omeWR0,iv:Y75zxwOTb5TI7wEDtrQd5914aD0kmNil1QFQpDS0JD8=,tag:0Pw/LU8slYkEAWGeyQ7ZIg==,type:str]
    DBURI: ENC[AES256_GCM,data:1/rhrHqRM7+BJ2uNNlz8fGKyej3aNmM+nEqiYWVkXjdqrM0=,iv:1NfJQG2ARDyxvJXV0s39o8XOEhd1N7B2+T5zozZjs1k=,tag:50nYsbgSVQCb/q2v5YZeSQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:B9bvAfpPrwppSlGzjP40v+DRT33YoaZXYukH6aV3/U0dFEoMYfFxlAdzpkPl1uLojTdXd5Xv+lBiOzFsCDqIeVua1ItCTalC,iv:rHWB/qqOdQ6mQh279iVKyQ2Cv8VHhgeB0+KdCpmxpzA=,tag:4+gU7AOtSg+do2RABFhATA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:XUy8IGKoS7ItSEgqPmsyUabr+pjj4jM/L25VY65ESkiFWnU=,iv:+7IfaXGGokiSJNfkWxJfTJi6VsuNQnH/oKAB3Ltth98=,tag:2vz68Ts4AiB10WOIKHyo6A==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:ivUxsclju9jhALXFBtEopu1Gb/xYlNuWloZSxica5wk=,iv:/F/QISJCkCLzkBLhtjmMmzvLWhskuqm08EOnEttS0Ao=,tag:oBWMbUskteSpffeYl/uEKA==,type:str]
    SESSION: ENC[AES256_GCM,data:amnBNJj0sbc/j8gUbGhvGTtPbA==,iv:9GNGt1ylTAQPinuGj3m7eAYzFuVfj7dC45pYNsvOsMs=,tag:c7DeN9AQQYwZ2qfuwTNaHA==,type:str]
    SESSION_KEY: ENC[AES256_GCM,data:8A0Ys+oBnT5ugAQLSKFZUEGIoA==,iv:5U0ncPJ6LtYbTSsQo5hSNp1kaIKLkxdb2YURpCoba4Q=,tag:pnUjlIqcUYAdLsnFrf36qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kk3kuv24cpkd00cmdvgmzuzppnpt3svtgdguejulzm2nktg3gdfq0ywdgm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVy93OXRSTTFNNGVkMGZy
            MWlqd0F0RDJtVDh6bGplaXk4TzU3VWpCL3hVCmF0aStzQXJUamhjMTMvK3F5eFFX
            Wkcrb3N2aEd4cldDQ25vNzdnUW1lTE0KLS0tIFhIRGkxUWdKWkRuUURKWVo0ZnRN
            YWtVKzZTRUFjSmF2MG5RdklRb0hHd2cKuxNGczNqapxJrnKWqk4FVowyeVUdMhFQ
            C0YBDvIZp347QWJMSqpGbQG2XZptNr+h4tgaeBb1AVyIRbtR5L7d0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T20:24:11Z"
    mac: ENC[AES256_GCM,data:ahBUOkXuVPjECk+ZBy1IAAwydQCvUVdxPWR8Czk8uTAMzLfmsMrRzMXeAULEXesM8grVEIA/n2LtNFHDPDbXQysR1FbtOIKME2OY0wrpn5KsAT2y4EcWrji5CcEnmVtv2aftn8LuXFY5aa0cKAV5s8qNU862IfUN0RG3HlO3Skk=,iv:+31STFBZv5l+C2E4DEa4dzbMnL65XUY9/83LVIdIkNs=,tag:4QPw5Z9s0DjUbaTx2XO5Mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
