apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: masters-pool
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/dgunzy/masters-pool.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: masters-pool
  namespace: flux-system
spec:
  interval: 1m
  path: ./kube
  prune: true
  sourceRef:
    kind: GitRepository
    name: masters-pool
  decryption:
    provider: sops
    secretRef:
      name: sops-age