apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/my-cluster/kube-system/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system