apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
metadata:
  name: kube-system
  namespace: kube-system
patches:
- path: patch.yaml
  target:
    kind: Deployment
    name: metrics-server
    namespace: kube-system