apiVersion: apps/v1
kind: Deployment
metadata:
  name: cabot-cup
  namespace: my-cluster
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: ghcr.io/dgunzy/ejs-cabot-app:latest
        ports:
          - name: web
            containerPort: 3000
