apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - ../apps/demo-app/flux-kustomization.yaml
  - ../ingress-nginx/flux-kustomization.yaml