apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - ../ingress-nginx/flux-kustomization.yaml
  - ../apps/cabot-cup/flux-kustomization.yaml
  - ../cert-manager/flux-kustomization.yaml
  - ../apps/cabot-book/flux-kustomization.yaml
  - ../kube-system/metrics-server/flux-kustomization
